package fp.tipo;

public enum Tipos {
	//nOTA EN EL DATASET LOS TIPOS NO SE CORRESPONDEN A LOS DE PRIMERA GENERACION
NONE,NORMAL,FIGHTING,FLYING,POISON,GROUND,ROCK,BUG,GHOST,STEEL,FIRE,WATER,GRASS,ELECTRIC,PSYCHIC,ICE,DRAGON,DARK,FAIRY
	
}
